Update the package.xml files with the latest Open Robotics maintainers
ros2/launch_ros pull request #183
Opened 2020-10-06 19:10 UTC by mjeronimo

See title :)

2020-10-06 19:18 UTC, clalancette requested changes
In general, when we remove maintainers we tend to move them to an `author` tag.  That's just to acknowledge the work they've done in the past.

2020-10-06 19:19 UTC, clalancette commented
You also need to add a `Signed-off-by` line to please the DCO bot.

2020-10-06 19:20 UTC, mjeronimo commented
@clalancette Ok, I'll update, thanks.

2020-10-06 19:53 UTC, clalancette requested changes
One more minor thing to fix, then looks good.  Thanks.

2020-10-06 19:53 UTC, clalancette commented on launch_testing_ros/package.xml
>    <maintainer email="pete.baughman@apex.ai">Pete Baughman</maintainer>
I'd go ahead and make Pete an `author` here.

2020-10-06 19:59 UTC, clalancette commented
Generally looks good, but you'll have to go back and rebase and sign all of the commits for the DCO bot.

2020-10-06 20:45 UTC, jacobperron approved these changes

2020-10-06 20:54 UTC, wjwwood approved these changes

2020-10-07 12:29 UTC, clalancette approved these changes

2020-10-07 16:36 UTC, merged