Fix "imported but not used" linters
ros2/launch_ros pull request #334
Opened 2022-11-29 15:23 UTC by Blast545

Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

2022-11-29 15:27 UTC, mjcarroll approved these changes

2022-11-29 15:27 UTC, Blast545 commented
I think it might be worth taking a look as to why this started appearing in the coverage jobs, and hasn't shown in the release/debug jobs. @Crola1702

2022-11-29 15:40 UTC, Blast545 commented
Galactic up to `launch_ros`, Linux CI:

[![Build Status](https://ci.ros2.org/job/ci_linux/17721/badge/icon)](https://ci.ros2.org/job/ci_linux/17721/)

2022-11-29 17:38 UTC, cottsay requested changes
Both of these are caused by typing annotations, and will appear with older Python interpreters. They should be marked with `#noqa`, not removed.

Here's where they're used:
https://github.com/ros2/launch_ros/blob/3c355ed49ba5e746d5e5ca454390bf6b6ac2fc2d/launch_ros/launch_ros/actions/load_composable_nodes.py#L82
https://github.com/ros2/launch_ros/blob/3c355ed49ba5e746d5e5ca454390bf6b6ac2fc2d/launch_ros/launch_ros/utilities/evaluate_parameters.py#L155

2022-11-30 15:27 UTC, Crola1702 commented
Running CI with new change: [![Build Status](https://ci.ros2.org/job/ci_linux/17726/badge/icon)](https://ci.ros2.org/job/ci_linux/17726/)

2022-12-02 18:26 UTC, cottsay requested changes
We can disable the specific check that's failing. Additionally, flake8 calls for two spaces before an inline comment, but the unqualified `#noqa` was actually squelching that violation as well.

2022-12-02 18:26 UTC, cottsay commented on launch_ros/launch_ros/actions/load_composable_nodes.py
> +from typing import Text # noqa
```suggestion
from typing import Text  # noqa: F401
```

2022-12-02 18:26 UTC, cottsay commented on launch_ros/launch_ros/utilities/evaluate_parameters.py
> +import pathlib # noqa
```suggestion
import pathlib  # noqa: F401
```

2022-12-06 14:24 UTC, Crola1702 commented
Running CI again with the latest commits:
[![Build Status](https://ci.ros2.org/job/ci_linux/17759/badge/icon)](https://ci.ros2.org/job/ci_linux/17759/)

2022-12-06 18:06 UTC, cottsay approved these changes

2022-12-07 14:12 UTC, merged