added type hinting in launch_ros/launch_testing_ros/test/examples
ros2/launch_ros pull request #385
Opened 2023-11-20 21:06 UTC by yaswanth1701

Closes issue #366 
SUMMARY:
Added python type hinting support for all the examples in  ```launch_ros/launch_testing_ros/test```

2023-11-20 21:16 UTC, clalancette requested changes
The linters are complaining; you can see what to fix in https://build.ros2.org/job/Rpr__launch_ros__ubuntu_jammy_amd64/161/testReport/junit/launch_testing_ros.test/test_flake8/test_flake8/ .

2023-11-20 21:34 UTC, yaswanth1701 commented
yes !! working on it

2023-11-20 22:37 UTC, yaswanth1701 commented
Hi @clalancette,  I am done with the required changes can you please review them?

2023-11-21 13:24 UTC, clalancette requested changes
I've left a bunch of comments.  In short, let's not make unrelated changes in this PR, and just stick to the type annotation.

2023-11-21 13:24 UTC, clalancette commented on launch_testing_ros/test/examples/check_node_launch_test.py
> +    def wait_for_node(self, node_name: str, timeout=8.0):
```suggestion
    def wait_for_node(self, node_name: str, timeout: float=8.0):
```

2023-11-21 13:24 UTC, clalancette commented on launch_testing_ros/test/examples/set_param_launch_test.py
> +            'demo_parameter_1', value=state).to_parameter_msg()]
Do we need to make this change?

2023-11-21 13:24 UTC, clalancette commented on launch_testing_ros/test/examples/check_msgs_launch_test.py
> +            target=lambda node: rclpy.spin(node), args=(self,))
Also, I can't put a comment up there, but `__init__` in this class should also have a type annotation on the `name` parameter.

2023-11-21 13:56 UTC, clalancette commented
> I am sorry I created a lot of mess here, I think force pushing from the start

Force pushing is just fine; I'd prefer to do that rather than create a new PR.

2023-11-21 14:15 UTC, yaswanth1701 commented
okay, I will close this PR and create a new one.

2023-11-21 14:15 UTC, closed without merging