Autostarting lifecycle nodes and example launch file demo
ros2/launch_ros pull request #430
Opened 2024-12-20 00:11 UTC by SteveMacenski

This resolves most of #418 which implements autostarting lifecycle nodes. 

You'll notice a new `is_lifecycle_node` attribute of the node and lifecycle nodes which is needed to remove a circular dependency on the LifecycleNode within the `LifecycleTransition` class which only is type checking. I replace this type check with checking if a non-None object (1) has the attribute at all and (2) has a lifecycle attribute with appropriate logging between the difference of a non-lifecycle node being attempted vs a non-node. This has been tested as well to function using the demos. 

The next steps here are to enable composition nodes to also have this feature, but running into a snag for the day in its implementation whereas `LifecycleTransition` doesn't work since it doesn't have the event handlers registered. Moving all that over seems pretty clunky so I'm mulling next steps.

2025-01-02 19:52 UTC, SteveMacenski commented
@mjcarroll can I get a review on this now that we're back from the holidays? :-)

2025-01-06 11:31 UTC, doisyg commented
That would be amazing to have this part of the standard launch!
(and I can already think about a next step: choose if you want to start in `Unconfigured`, `Inactive` or `Active`)

2025-01-16 17:45 UTC, SteveMacenski commented
@mjcarroll can I request a review? :heart:

2025-01-16 21:03 UTC, wjwwood requested changes
A few questions, but looking pretty good. Thanks for the contribution!

2025-01-16 21:03 UTC, wjwwood commented on launch_ros/launch_ros/actions/lifecycle_node.py
> +                ),
Shouldn't you wait for the transition to configure to complete before sending the transition to activate?

2025-01-16 21:03 UTC, wjwwood commented on launch_ros/launch_ros/actions/load_composable_nodes.py
> +                )
Similar comment here about waiting before transitioning, rather than fire-forget with two subsequent transitions.

2025-01-16 21:03 UTC, wjwwood commented on launch_ros/launch_ros/actions/load_composable_nodes.py
> +            return autostart_actions
I think this could just be:

```suggestion
        return autostart_actions
```

But if you want to call out to super I think that's ok. We just know (at least for now) that `launch.Action` always returns `None`:

https://github.com/ros2/launch/blob/a93ce70943c65b938d38eab78322dc27722b7a6f/launch/launch/action.py#L123-L129

But that being said, in case someone changes the base class of this class and doesn't notice this part of the code, calling super defensively isn't a bad idea.

Leave it or change it, doesn't matter to me, just wanted to point it out.

2025-01-16 21:03 UTC, wjwwood commented on launch_ros/launch_ros/actions/node.py
> +        autostart: Optional[bool] = False,
Why does this need to be part of the Node action API? Doesn't it only need to be on a LifecycleNode action?

2025-01-16 21:03 UTC, wjwwood commented on launch_ros/launch_ros/descriptions/composable_node.py
> +        autostart: Optional[bool] = False,
Same comment as for Node action.

2025-01-16 21:03 UTC, wjwwood commented on launch_ros/launch_ros/event_handlers/on_state_transition.py
> +        target_lifecycle_node: Optional[SomeSubstitutionsType] = None,
Why does this need to be a `SomeSubstitutionsType`? Not saying it's wrong, just curious what use case you have in mind?

2025-01-16 21:03 UTC, wjwwood commented on launch_ros/launch_ros/event_handlers/on_state_transition.py
> +        target_lifecycle_node: Optional[SomeSubstitutionsType] = None,
And further, I'm not sure this works because this would essentially be a type name as a string, but before this was a _value_ not a _type_, and we passed that instance of the object in to the event as `event.action`. So maybe I do think this isn't right.

2025-01-16 21:03 UTC, wjwwood commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        :param name: The name of the lifecycle node.
Might want to clarify here whether or not the name needs to be fully qualified or not.

2025-01-16 21:03 UTC, wjwwood commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +            event = StateTransition(action=self, msg=msg)
I don't think you can pass `action=self` here, see: https://github.com/ros2/launch_ros/blob/f9ab9371824d470bca47602bc7d277eb2217c90d/launch_ros/launch_ros/events/lifecycle/state_transition.py#L42

2025-01-16 21:03 UTC, wjwwood commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        response = response_future.result()
`Future.result()` will throw for you, see:

https://github.com/ros2/rclpy/blob/2b38e662b3635fffe5b68309f75e39f9e7441602/rclpy/rclpy/task.py#L107-L118

2025-01-16 21:03 UTC, wjwwood commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        if not typed_event.lifecycle_node_matcher(self):
Again, if the user emits their own `ChangeState` pointing to their `LifecycleNode` action, then this will not match it right?

2025-01-16 22:28 UTC, SteveMacenski commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        if not typed_event.lifecycle_node_matcher(self):
This is copy+pasted from the lifecycle node abstracted into a manager to share with composition node. I'd prefer not to make functional changes in this PR if that's OK with you. This has been the state of things previously and just reorganized to be shared among multiple node types

But w.r.t. this comment: No, actually! The subscription keeps them aligned: https://github.com/ros2/launch_ros/blob/84c44de2ab85eb03e55ddcd6491a79eceba38482/launch_ros/launch_ros/utilities/lifecycle_event_manager.py#L127-L131

2025-01-16 22:28 UTC, SteveMacenski commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        response = response_future.result()
This is copy+pasted from the lifecycle node abstracted into a manager to share with composition node. I'd prefer not to make functional changes in this PR if that's OK with you. This has been the state of things previously and just reorganized to be shared among multiple node types

2025-01-16 22:28 UTC, SteveMacenski commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +            event = StateTransition(action=self, msg=msg)
This works - this has all been tested with the examples I provided.

2025-01-16 22:28 UTC, SteveMacenski commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        :param name: The name of the lifecycle node.
This is copy+pasted from the lifecycle node abstracted into a manager to share with composition node. I don't really know one way or another, I'm not the original author.

2025-01-16 22:28 UTC, SteveMacenski commented on launch_ros/launch_ros/event_handlers/on_state_transition.py
> +        target_lifecycle_node: Optional[SomeSubstitutionsType] = None,
Because I needed this to not be specifically a `LifecycleNode` due to circular dependencies using this within LifecycleNode itself for the transitioning. So, to make sure that it is still a lifecycle-compliant node, I used the Optional type and checked that it was a proper instance of a lifecycle-compliant node using `is_lifecycle_node` (since components, lifecycle, and node in launch_ros can all be used to launch a rclcpp::LifecycleNode)

> Im not sure this works 

I can't comment on the reasoning you have for it not working, but I can say from testing with the examples I provided that it does indeed work.

2025-01-16 22:28 UTC, SteveMacenski commented on launch_ros/launch_ros/descriptions/composable_node.py
> +        autostart: Optional[bool] = False,
Composable nodes can be also lifecycle nodes -- see Nav2 :-) 

This is actually the main application for which I'm opening this PR. Its very difficult to work with lifecycle-components in launch_ros. There's no technical way (before this) to transition up a component that's a lifecycle node. The other events that are used by the launch_ros.LifecycleNode reject updates from other node types.

2025-01-16 22:28 UTC, SteveMacenski commented on launch_ros/launch_ros/actions/node.py
> +        autostart: Optional[bool] = False,
Lifecycle nodes can be launched as `launch_ros.Node`'s

2025-01-16 22:28 UTC, SteveMacenski commented on launch_ros/launch_ros/actions/load_composable_nodes.py
> +            return autostart_actions
I am copying the styling of the existing codebase here, this is how its done in all other locations I viewed, so I'd say we should leave it.

2025-01-16 22:33 UTC, SteveMacenski commented on launch_ros/launch_ros/actions/lifecycle_node.py
> +                ),
LifecycleTransition handles this for us. 

1. We build a set of possible change events to emit at some point: https://github.com/ros2/launch_ros/blob/84c44de2ab85eb03e55ddcd6491a79eceba38482/launch_ros/launch_ros/actions/lifecycle_transition.py#L145-L155
2. Then we trigger the events when a transition occurs making it possible for the next transition to occur https://github.com/ros2/launch_ros/blob/84c44de2ab85eb03e55ddcd6491a79eceba38482/launch_ros/launch_ros/actions/lifecycle_transition.py#L167-L174
3. The actual event is performed when  https://github.com/ros2/launch_ros/blob/84c44de2ab85eb03e55ddcd6491a79eceba38482/launch_ros/launch_ros/actions/lifecycle_transition.py#L195-L196

Thus, the events occur when they're possible and only when they're possible given the state already in the handy work done by the `lifecycle_transition.py` authors :smile:

2025-01-16 22:33 UTC, SteveMacenski commented on launch_ros/launch_ros/actions/load_composable_nodes.py
> +                )
See above. Its a copy paste so we can resolve above and I can apply both if any changes are necessary.

2025-01-17 03:25 UTC, SteveMacenski commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +            event = StateTransition(action=self, msg=msg)
After looking into this in detail, you are right that this was non-functional. I tested node transitions up on Lifecycle/Composition, but didn't check if the transition_event callback was properly matching events.

I fixed it by making the `==` operator look at the lifecycle node rather than the lifecycle event management object & passing in the lifecycle node to the constructor. 

I tried also working on this by changing the matchers to use the `node_name` in the places that they directly compare the `event.actions == node`-style calls. It worked equally as well, but I felt it better to change less than more in the matchers in case some folks rely on it for very particular behavior.

2025-01-17 03:25 UTC, SteveMacenski commented
@wjwwood I addressed all of your comments and made a fix

2025-01-28 21:23 UTC, wjwwood commented on launch_ros/launch_ros/actions/node.py
> +        autostart: Optional[bool] = False,
I mean, it makes sense to me that a standard Node doesn't expect an autostart keyword. I would prefer it not to arguments it never uses.

2025-01-28 22:19 UTC, wjwwood commented on launch_ros/launch_ros/event_handlers/on_state_transition.py
> +        target_lifecycle_node: Optional[SomeSubstitutionsType] = None,
> Isn't LifecycleNode a type and Optional[SomeSubstitutionsType] a type? 

I mean, yes, but that's like saying replacing `rclcpp::Node` with `std::string` in c++ is ok because they're both types...

If it's just an issue with circular dependencies then for the Type annotations you can just string quote the type, e.g.:

```suggestion
        target_lifecycle_node: Optional['LifecycleNode'] = None,
```

Or I think you can do something like this at the top of the file:

```
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ... import LifecycleNode
```

See: https://stackoverflow.com/a/39757388

2025-01-28 22:20 UTC, wjwwood commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        :param name: The name of the lifecycle node.
Well you may have copy-pasted it, but it's still important for you and the users to know what needs to be passed here. If you're only forwarding it to the other constructor, then maybe you can simply reference it from here rather than copy-pasting the explanation.

2025-01-28 22:29 UTC, wjwwood commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        if not typed_event.lifecycle_node_matcher(self):
> This is copy+pasted from the lifecycle node abstracted into a manager to share with composition node. I'd prefer not to make functional changes in this PR if that's OK with you. This has been the state of things previously and just reorganized to be shared among multiple node types

I get where you're coming from, but in this case your copy-paste is into a different class with a different type where you also use `self`, so you're essentially changing the behavior even though it's a copy-paste because of that.

I don't see  how the subscriptions keep them aligned? The `typed_event.lifecycle_node_matcher` is user defined and may not look at the subscription at all. Plus the matcher explicitly expects a `LifecycleNode` here not the type of self in your copy-pasted code:

https://github.com/ros2/launch_ros/blob/f9ab9371824d470bca47602bc7d277eb2217c90d/launch_ros/launch_ros/events/lifecycle/change_state.py#L92

Here's an example that won't likely work:

https://github.com/ros2/launch_ros/blob/f9ab9371824d470bca47602bc7d277eb2217c90d/launch_ros/examples/lifecycle_pub_sub_launch.py#L50

That is expecting the actions objects to match...

2025-01-28 22:31 UTC, wjwwood commented on launch_ros/launch_ros/descriptions/composable_node.py
> +        autostart: Optional[bool] = False,
I guess I find it weird still that you'd pass an argument that may or may not be ignored. Wouldn't using the type system be good here, and having a composable lifecycle node type class to disambiguate it?

If we have a use case for a generic type that can be either a lifecycle node or something else, then maybe this is fine, but I believe you always know if a node is going to be lifecycle or not, otherwise you wouldn't pass autostart. Also, if you _think_ the node is lifecycle, and so you pass autostart, but it actually isn't, wouldn't you want to catch that? Seems like a bug waiting to be missed.

2025-01-28 22:47 UTC, wjwwood commented on launch_ros/launch_ros/actions/lifecycle_node.py
> +                ),
Ok, makes sense, I missed the magic ✨ that `LifecycleTransition` was doing. That seems fine.

2025-01-28 22:48 UTC, wjwwood commented on launch_ros/launch_ros/actions/node.py
> +        autostart: Optional[bool] = False,
I think it would be ok to check for the argument and raise a better error if you think it would help too.

2025-01-28 22:49 UTC, wjwwood commented on launch_ros/launch_ros/event_handlers/on_state_transition.py
> +        target_lifecycle_node: Optional[SomeSubstitutionsType] = None,
btw, didn't mean to come off snarky with the c++ comparison, but that is the sort of what's happening with the `SomeSubstitutionsType`, since that type essentially gets resolved into a string.

2025-01-28 22:50 UTC, wjwwood commented
I sent a few responses, resolved a few others. Sorry it took so long to reply, I'll try to be quicker on the next iteration. Thanks again!

2025-01-30 01:27 UTC, SteveMacenski commented on launch_ros/launch_ros/actions/node.py
> +        autostart: Optional[bool] = False,
> I mean, it makes sense to me that a standard Node doesn't expect an autostart keyword. I would prefer it not to arguments it never uses.

A-OK, I think that's reasonable. Removing it. I think you're right and that error is acutally pretty semantically easy to understand 

> TypeError: Action.__init__() got an unexpected keyword argument 'autostart'

Completed in: a4ca018188b67fb7158bb559d6d904ac4b613c57

2025-01-30 01:29 UTC, SteveMacenski commented on launch_ros/launch_ros/event_handlers/on_state_transition.py
> +        target_lifecycle_node: Optional[SomeSubstitutionsType] = None,
Hey, no worries. I'm not overly familiar with this in Python3 so point taken

Fixed in 4c06f44e78c05ace536932a759ed4882aa636481

2025-01-30 01:32 UTC, SteveMacenski commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        :param name: The name of the lifecycle node.
Actually, I have a nice cop-out for this. In the last changes, I actually removed the name argument to instead give the lifecycle node itself to handle the matcher issue. So that argument is no longer present :smile: 

I updated the outdated docstring entry for the lifecycle node object in  1ff9bacccca5b4ebe5e7493d61d6a8848073083b

2025-01-30 03:01 UTC, SteveMacenski commented on launch_ros/launch_ros/descriptions/composable_node.py
> +        autostart: Optional[bool] = False,
>  having a composable lifecycle node type class to disambiguate it

I both agree and disagree - but I agree that having a lifecycle-component would make it absolutely clear. 

Completed in f445bd9bf0d24288daeacce02dd37176c730a802

2025-01-30 03:02 UTC, SteveMacenski commented
I appreciate it, I know this isn't the most active project in the ROS core ecosystem, so I appreciate the attention here :-)

2025-01-30 03:15 UTC, SteveMacenski commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        if not typed_event.lifecycle_node_matcher(self):
I override the `__eq__` operator so that the lifecycle node object is used for those comparisons :-) 

```
    def __eq__(self, other):
        return self.__lifecycle_node == other
```

After the changes in the other comments, I tried all of the launch examples again and they all work (including setting autostart to false, true, and removed): 

Node via `pub_sub_launch.py`:
* No autostart, gives error if one is given

Lifecycle node via `lifecycle_pub_sub_launch.py` with external triggers:
* The registered event handlers and event emiting works properly, nodes come up as expected 
* I think this was your concern, this does work. 

Lifecycle nodes via `lifecycle_autostart_pub_sub_launch.py` with internal autostart:
* Autostart = true, autostarts and pub/sub is logged. Autostart logging is seen.
* Autostart=false, system comes up, no pub/sub logging. Autostart logging is not seen.
* Autostart not set, system comes up, no pub/sub logging. Autostart logging is not seen.

Lifecycle component nodes via `lifecycle_component_autostart_pub_sub_launch.py`:
* Autostart=true, Autostart logging is seen.
* Autostart=false, Autostart logging is not seen.
* Autostart not set, Autostart logging is not seen.

Note for the last one `lifecycle_component_autostart_pub_sub_launch.py`, the components themselves are not lifecycle enabled, so the logging is used to validate that the autostart keyword is parsed and will setup the transition. They end up publishing / subscribing regardless of autostart since they're not actually lifecycle nodes at all. Unfortunately the [lifecycle listener / talker demos](https://github.com/ros2/demos/blob/rolling/lifecycle/src/lifecycle_listener.cpp) are not components for me to use, so I have to use the components that we have. I did test and do debug logging to make sure this is correct and I'm confident that it is.

2025-02-04 18:26 UTC, wjwwood commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        if not typed_event.lifecycle_node_matcher(self):
> I override the __eq__ operator so that the lifecycle node object is used for those comparisons :-)

That's kind of my point, which is that the type annotations are indicating that you should expect something different. It just so happens that the matchers we use only do `==`, but a user sees it takes a `LifecycleNode` and may think they can call anything available on that class in their matcher, but that's not the case because you're passing a different class and in one case making it appear to be correct. It would be better to just pass the correct class, or have the new class actually inherit from `LifecycleNode`, or actually change the API of the callback for matchers so the false expectation is avoided.

My preference is for one of the first two options honestly. Trying to pass off this new class as if it were a `LifecycleNode` seems a bit too clever to me. It's gonna be surprising and confusing to someone at some point, in my opinion.

2025-02-04 18:26 UTC, wjwwood commented
Sorry, one more iteration on the matchers.

2025-02-04 20:30 UTC, SteveMacenski commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        if not typed_event.lifecycle_node_matcher(self):
I did this to avoid making other changes to matchers. I actually did this originally but backed that out because the `launch.events` matcher [1] compares the nodes rather than any specific attribute. The existing [lifecycle pub/sub launch example](https://github.com/ros2/launch_ros/blob/rolling/launch_ros/examples/lifecycle_pub_sub_launch.py#L50) uses that matcher and would break the behavior if `==` didn't match. Since `launch.events` is pretty core, I didn't want to introduce any change that would break that behavior, even though the [`launch_ros.events` versions work perfectly for us](https://github.com/ros2/launch_ros/blob/rolling/launch_ros/launch_ros/events/matchers/matches_node_name.py#L25-L29 [2]. The launch_ros version honestly seem better to me by being less fragile based on attributes rather than comparing full objects.  However anyone using the `launch.events` version rather than the `launch_ros.events` version would see a break, so I implemented the `__eq__` to make them both continue to work as expected. 

[1] https://github.com/ros2/launch/blob/rolling/launch/launch/events/matchers.py#L22-L24
[2] https://github.com/ros2/launch_ros/blob/rolling/launch_ros/launch_ros/events/matchers/matches_node_name.py#L25-L29

> It would be better to just pass the correct class, or have the new class actually inherit from LifecycleNode ... My preference is for one of the first two options honestly. 

I'm always open for critique - I don't really understand the suggestion though, can you clarify your vision for: "pass the right class"?  

I odn't think the new class is good since it would make users have to use a `LifecycleAutostartingNode` object just to obtain the `autostart` field, which is unnatural and seems confusing. Plus, it would require me to duplicate code. I'm on board with the semantic difference between `ComposableLifecycleNode` and `ComposableNode`, but having a second `LifecycleNode` for a feature that is intrinsically linked to lifecycle nodes is strange.   

> Trying to pass off this new class as if it were a LifecycleNode seems a bit too clever to me. It's gonna be surprising and confusing to someone at some point, in my opinion.

Pending on understanding your point about "pass the right class", I think what is currently here is a better solution. Its a little clever, but not really much so, I don't think. Especially if documented (which I can improve) and keeps all matchers working

2025-02-04 20:31 UTC, SteveMacenski commented
See updated comment :-)

2025-02-07 20:03 UTC, wjwwood commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        if not typed_event.lifecycle_node_matcher(self):
>  I don't really understand the suggestion though, can you clarify your vision for: "pass the right class"?

You already have a new class, `LifecycleEventManager`, which you're passing on this line as `self`. My point was that you should either pass `self. __lifecycle_node` here or have `LifecycleEventManager` inherit from `LifecycleNode` since that is the type that the matcher is expecting. That way you don't need to override the `==` behavior and the matcher is getting what it expects and future changes that might do more than `==` will continue to work.

2025-02-07 20:04 UTC, wjwwood commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        if not typed_event.lifecycle_node_matcher(self):
Naively, this is a concrete change that would satisfy me here:

```suggestion
        if not typed_event.lifecycle_node_matcher(self. __lifecycle_node):
```

Though that might not work for some other reason, in which case you might have to do the inheritance.

2025-02-07 20:15 UTC, wjwwood commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        if not typed_event.lifecycle_node_matcher(self):
Well, I guess not, because if there's something in the `LifecycleEventManager` class that you need in the matcher, you could just do `lifecycle_node.__lifecycle_event_manager` (which btw there should probably be an accessor for the event manager from the lifecycle node).

2025-02-07 20:33 UTC, wjwwood requested changes
looks really close

I continued our conversation on the other thread, and pointed out a potential issue with how autostart is being typed and documented. Other than that, it's mostly cleanup requests after your most recent set of changes.

2025-02-07 20:33 UTC, wjwwood commented on launch_ros/launch_ros/actions/lifecycle_node.py
> +        autostart: Optional[bool] = False,
I think a docstring entry about this parameter here would be helpful. It's not clear to me why it's optional and what happens when it's `None`.

2025-02-07 20:33 UTC, wjwwood commented on launch_ros/launch_ros/actions/lifecycle_node.py
> +        if self.node_autostart:
Do you need to have a condition here for when autostart is `None`? Currently this condition is implicitly like `if self.node_autostart is not None and self.node_autostart is True`, which is maybe what you want, but also then why can it ever be `None`?

2025-02-07 20:33 UTC, wjwwood commented on launch_ros/launch_ros/actions/node.py
> +
I don't think this should be added to `Node` either. It's a bad smell for lifecycle to be mentioned in the Node class at all. If we wanted to add another kind of node in the future we don't want to have to change the node class each time. Can we find a way to not need these two functions on node? This seems like a job for the type system.

2025-02-07 20:33 UTC, wjwwood commented on launch_ros/launch_ros/descriptions/composable_node.py
> +import launch
I don't think this is needed anymore.

2025-02-07 20:33 UTC, wjwwood commented on launch_ros/launch_ros/descriptions/composable_node.py
> +from launch_ros.utilities import LifecycleEventManager
I don't think this is needed anymore.

2025-02-07 20:33 UTC, wjwwood commented on launch_ros/launch_ros/descriptions/composable_node.py
> +
It would be great to avoid this addition too.

2025-02-07 20:57 UTC, wjwwood reviewed
Sorry, after re-reviewing the new class you recently added I found some more things that should be looked into.

2025-02-07 20:57 UTC, wjwwood commented on launch_ros/launch_ros/descriptions/composable_lifecycle_node.py
> +        condition: Optional[Condition] = None,
You can just forward these arguments to the ComposableNode class, only adding `autostart`, instead of redeclaring them here. This is also more robust to future changes as new arguments to `ComposableNode` will automatically be accepted here too.

You can use `kwargs` to do this. Take a look at how `LifecycleNode` is done. It duplicates a few parameters that it needs to use, which is fine, but pass the rest along entirely in `kwargs`.

2025-02-07 20:57 UTC, wjwwood commented on launch_ros/launch_ros/descriptions/composable_lifecycle_node.py
> +        return self._ComposableNode__package
We should try to use accessors here. Rather than reach around the public/private name mangling.

2025-02-07 20:57 UTC, wjwwood commented on launch_ros/launch_ros/descriptions/composable_lifecycle_node.py
> +        self.__node_name = self._ComposableNode__node_name
Same here, use an accessor. Make one if there's not one.

2025-02-07 20:57 UTC, wjwwood commented on launch_ros/launch_ros/actions/load_composable_nodes.py
> +
I won't block my review on this, but I wanted to point out that adding this lifecycle specific logic here isn't ideal. Instead, it would be great to have something like `on_execute(context) -> List[Action]` on `ComposableNode`, calling that for each `node_description` and accumulating the actions returned to be later returned at the end of this function as you're doing with `autostart_actions` but generically.

Then the `on_execute` in `ComposableNode` could be empty for now, and all of this highlighted logic could be moved into `LifecycleComposableNode`'s override of `on_execute()`. That way this class never has to understand anything about lifecycle nodes.

2025-02-07 20:57 UTC, wjwwood commented on launch_ros/launch_ros/actions/load_composable_nodes.py
> +                node_description.init_lifecycle_event_manager(node_description, context)
This is related to my comment about an `on_execute` "virtual" function on the composable node classes, but it's weird to be passing itself into this function. I think this could just be:

```suggestion
                node_description.init_lifecycle_event_manager(context)
```

2025-02-07 20:57 UTC, wjwwood commented on launch_ros/launch_ros/descriptions/composable_lifecycle_node.py
> +        self.__lifecycle_event_manager.setup_lifecycle_manager(context)
Following up on my previous comment, this could just be:

```suggestion
    def init_lifecycle_event_manager(self, context: launch.LaunchContext) -> None:
        # LifecycleEventManager needs a pre-substitution node name
        self.__lifecycle_event_manager = LifecycleEventManager(self)
        self.__lifecycle_event_manager.setup_lifecycle_manager(context)
```

Also, the `node_name` line seems completely unnecessary? Either that or the line in the constructor of this class where you do `self.__node_name = self._ComposableNode__node_name` isn't needed?

2025-02-07 23:25 UTC, SteveMacenski commented on launch_ros/launch_ros/actions/lifecycle_node.py
> +        autostart: Optional[bool] = False,
Done for docstring, I remove None optionality

2025-02-07 23:25 UTC, SteveMacenski commented on launch_ros/launch_ros/actions/lifecycle_node.py
> +        if self.node_autostart:
I remove None optionality

2025-02-07 23:25 UTC, SteveMacenski commented on launch_ros/launch_ros/actions/node.py
> +
Done :+1:

2025-02-07 23:25 UTC, SteveMacenski commented on launch_ros/launch_ros/descriptions/composable_node.py
> +import launch
Removed

2025-02-07 23:25 UTC, SteveMacenski commented on launch_ros/launch_ros/descriptions/composable_node.py
> +from launch_ros.utilities import LifecycleEventManager
Removed

2025-02-07 23:25 UTC, SteveMacenski commented on launch_ros/launch_ros/descriptions/composable_node.py
> +
Done :+1:

2025-02-07 23:25 UTC, SteveMacenski commented on launch_ros/launch_ros/descriptions/composable_lifecycle_node.py
> +        condition: Optional[Condition] = None,
OK, done!

2025-02-07 23:25 UTC, SteveMacenski commented on launch_ros/launch_ros/descriptions/composable_lifecycle_node.py
> +        return self._ComposableNode__package
Totally agree :+1: Done

2025-02-07 23:25 UTC, SteveMacenski commented on launch_ros/launch_ros/descriptions/composable_lifecycle_node.py
> +        self.__node_name = self._ComposableNode__node_name
Totally agree :+1: Done

2025-02-07 23:25 UTC, SteveMacenski commented on launch_ros/launch_ros/actions/load_composable_nodes.py
> +
I don't disagree it would nicely bin the lifecycle logic in discrete places, but the composable node / lifecycle composable nodes are both descriptions not actions. I think it would be against the design intent of the object to have execution-related methods like that. 

So, I think this can be left as-is?

2025-02-07 23:25 UTC, SteveMacenski commented on launch_ros/launch_ros/actions/load_composable_nodes.py
> +                node_description.init_lifecycle_event_manager(node_description, context)
I agree, this is an artifact of moving the logic from lifecycle node to the composition node. 

Completed

2025-02-07 23:25 UTC, SteveMacenski commented on launch_ros/launch_ros/descriptions/composable_lifecycle_node.py
> +        self.__lifecycle_event_manager.setup_lifecycle_manager(context)
Done - actually did this change from the previous comment before I got down to this one :laughing: 

> Also, the node_name line seems completely unnecessary? Either that or the line in the constructor of this class where you do self.__node_name = self._ComposableNode__node_name isn't needed?

It is actually necessary. The node name at the start is a substitution and we need toperform the substitution at this point to get the actual value to pass into the lifecycle event manager.

2025-02-07 23:46 UTC, SteveMacenski commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        if not typed_event.lifecycle_node_matcher(self):
> You already have a new class, LifecycleEventManager, which you're passing on this line as self. My point was that you should either pass self.__lifecycle_node here 

This is another obvious simplicity from heritage decisions where this started by only passing in the lifecycle node's name, not the object itself. Now that we have the object, that is exactly the right thing to do for the case of `_on_change_state_event`. I'll do that in a commit since there's absolutely no good reason not to do that. 

However, that doesn't address the issue of the `launch.event` matcher which uses the `==` operator - which can be defined externally by a user. [For example in the `lifecycle_pub_sub_launch.py` demo example](https://github.com/ros2/launch_ros/blob/rolling/launch_ros/examples/lifecycle_pub_sub_launch.py#L50). I don't actually think (?) that deriving from the lifecycle node class would solve that issue either, since the `LifecycleEventManager` would then be of type `LifecycleNode`, but not the same instance of it. 

Edit: Actually, I just found a way around that. I can just pass in the lifecycle node into the state transition too `StateTransition(action=self.__lifecycle_node, msg=msg)`. 

This is done :sunglasses: 

Personally, I think the `launch.event` matcher is extremely fragile. Checking that specific instances match 

 > which btw there should probably be an accessor for the event manager from the lifecycle node

ACKed and done

2025-02-07 23:46 UTC, SteveMacenski commented
@wjwwood all of your comments have been addressed, I believe fully now

2025-02-11 18:21 UTC, wjwwood commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        if not typed_event.lifecycle_node_matcher(self):
> Personally, I think the launch.event matcher is extremely fragile. I feel like having the actions be required to have a name field which could be autogenerated as a hash if not provided would be better.

Not sure what you mean, but for XML having "named" instances of actions would be necessary/useful. But what you're describing (with autogeneration or hashing), isn't that just `id(action)`? Which btw is what `==` is checking when you call it by default:

https://docs.python.org/3/library/functions.html#id

2025-02-11 18:46 UTC, wjwwood approved these changes
lgtm

Had a few non-blocking questions, but I think this is good to go with passing CI.

2025-02-11 18:46 UTC, wjwwood commented on launch_ros/launch_ros/event_handlers/on_state_transition.py
> +        lifecycle_property = type(target_lifecycle_node).__dict__.get('is_lifecycle_node', None)
Just curious, but is `getattr(target_lifecycle_node, 'is_lifecycle_node', None)` not sufficient? https://docs.python.org/3/library/functions.html#getattr

2025-02-11 18:46 UTC, wjwwood commented on launch_ros/launch_ros/event_handlers/on_state_transition.py
> +                               ' target_lifecycle_node is not a lifecycle-enabled node.')
This diff is still a bit confusing to me, why is the original check not sufficient? Is it so we can support non-LifecycleNode based classes?

Also the why do we need the first new condition? It seems like it being either `None` or a `property` isn't important, but the second check definitely makes sense with `hasattr` and checking the value of `is_lifecycle_node`. Plus the two possible errors seem to be more or less the same (at least based on the error message).

2025-02-11 18:52 UTC, wjwwood commented
Rpr looks like it is failing due to a few small linter issues. After you fix that I'll run full CI with Windows and everything on ci.ros2.org unless someone else beats me to it.

2025-02-11 19:44 UTC, SteveMacenski commented on launch_ros/launch_ros/utilities/lifecycle_event_manager.py
> +        if not typed_event.lifecycle_node_matcher(self):
Huh, ok!

2025-02-12 02:29 UTC, SteveMacenski commented on launch_ros/launch_ros/event_handlers/on_state_transition.py
> +        lifecycle_property = type(target_lifecycle_node).__dict__.get('is_lifecycle_node', None)
The `__dict__` method checks the class definition if it has that attribute rather than the individual instance passed into the function. I thought this was a more strict type-checking method of handling it

2025-02-12 02:39 UTC, SteveMacenski commented on launch_ros/launch_ros/event_handlers/on_state_transition.py
> +                               ' target_lifecycle_node is not a lifecycle-enabled node.')
OnStateTransition is now used within the lifecycle node for the LifecycleTransition class, so we can't import `LifecycleNode` into the class or it creates circular dependencies. 

I'm going to fix these up to be more semantically meaningful. The first if is checking if we have the property at all in the class definition and the second is checking if its true. The second `hasattr(target_lifecycle_node, 'is_lifecycle_node')` is my defensive programming to make sure its there before calling it `target_lifecycle_node.is_lifecycle_node` 

I think its nice to have 2 different error logging for either if the property doesn't exist (i.e. not a lifecycle node at all) and also if the value present is non-true.

2025-02-12 02:44 UTC, SteveMacenski commented
Should be good to go. I also resolved the DCO sign off

2025-02-12 15:42 UTC, wjwwood approved these changes

2025-02-12 15:42 UTC, wjwwood commented on launch_ros/launch_ros/descriptions/composable_lifecycle_node.py
> +# from launch.utilities import ensure_argument_type
Looks like a left over.

2025-02-12 15:53 UTC, wjwwood commented on launch_ros/launch_ros/event_handlers/on_state_transition.py
> +                               ' target_lifecycle_node is not a lifecycle-enabled node.')
Oof, I thought the circular dependencies were only for the type annotations, I didn't realize we had actual circular dependencies. It's not great to have this kind of workaround for that, but maybe it's the best option atm. I would encourage you to make a comment about why we can't just use `isinstance(target_lifecycle_node, (LifecycleNode, type(None)))`, because it's not obvious why we're doing the type checking in this way.

I mean, it would be better to avoid it some other way and just check the type as we were before hand, but I don't want to hold this pr up more. I'll leave it there, but it doesn't leave me feeling awesome about the result.

One option, which I also don't love, is that you can import the class in the function, which should avoid any circular import issues, e.g.:

```python
        from ..actions import LifecycleNode
        if not isinstance(target_lifecycle_node, (LifecycleNode, type(None))):
            raise RuntimeError("OnStateTransition requires a 'LifecycleNode' action as the target")
```

It still feels like a hack, but at least it's more obvious what you're checking for than the indirect checks you have now.

2025-02-12 15:53 UTC, wjwwood commented
Looks like there's a test failure on the Rpr job, can you have a look and see if it's related/reproducible?

2025-02-12 15:56 UTC, wjwwood commented on launch_ros/launch_ros/event_handlers/on_state_transition.py
> +                               ' target_lifecycle_node is not a lifecycle-enabled node.')
You could, alternatively, import this class from the local function where `OnStateTransition` is used in `LifecycleNode`. That might make slightly more sense to me, but both are still kind of hacky.

2025-02-12 23:35 UTC, SteveMacenski commented on launch_ros/launch_ros/event_handlers/on_state_transition.py
> +                               ' target_lifecycle_node is not a lifecycle-enabled node.')
> One option, which I also don't love, is that you can import the class in the function, which should avoid any circular import issues, e.g.:

Done. that is actually done elsewhere in the codebase, so I think that's a better option since it is at least consistent

2025-02-12 23:36 UTC, SteveMacenski commented on launch_ros/launch_ros/descriptions/composable_lifecycle_node.py
> +# from launch.utilities import ensure_argument_type
Fixed. that was a copy+paste from the lifecycle node (removed from both)

2025-02-12 23:37 UTC, SteveMacenski commented
I don't think it relates to this - I just pushed a couple of new commits to fix your last 2 items - so we'll see :- )

2025-02-12 23:45 UTC, SteveMacenski commented
All passing now

2025-02-18 20:24 UTC, wjwwood commented
CI:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22559)](http://ci.ros2.org/job/ci_linux/22559/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16804)](http://ci.ros2.org/job/ci_linux-aarch64/16804/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=2075)](http://ci.ros2.org/job/ci_linux-rhel/2075/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23352)](http://ci.ros2.org/job/ci_windows/23352/)

2025-02-19 00:30 UTC, wjwwood commented
CI looks good, so I'm going to merge this now. Thanks again for the contribution!

> Any chance for a backport to Jazzy? This would be a really nice feature that could make some folks I'm talking to move to Jazzy if it were available

I think it should be fine to do so. The only changes to the API seem to be backwards compatible. Generally we don't backport features due to the risk of regression, but we can make exceptions when the risk is low. I'll ask for a second opinion on that though. I can at least open the pr for the backport and let another maintainer review/merge it as my second opinion.

2025-02-19 00:30 UTC, merged

2025-02-19 00:31 UTC, wjwwood commented
@mergifyio backport jazzy

2025-05-27 07:55 UTC, mojomex commented
Hi @wjwwood, is there any chance this could also be backported to Humble given that it still has two years until EOL?

2025-07-25 16:40 UTC, emersonknapp commented
@mergifyio backport humble

2025-07-25 16:41 UTC, christophebedard commented
@Mergifyio backport humble